# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cubism5Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cubism5Demo
  pod 'Live2DSdk', :path => '../'
end
